### ISSUE TITLE
Support `requests` for paths

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-service-worker#3]
ie:

```sh
/ipfs/QmHash/a
/ipfs/QmHash/a/b/c
```

Depends on:
- [ ] https://github.com/ipfs/js-ipfs/issues/837

**Comment by lidel** [comment]
Closing, this landed some time ago: 
- Path resolver and directory listing is provided by https://github.com/ipfs/js-ipfs-http-response
- and used by https://github.com/ipfs-shipyard/service-worker-gateway
