### ISSUE TITLE
Next milestone.

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-service-worker#6]
Given that we won't be able to count on Foreign Fetch. I'll pursue the `sw.ipfs.io` service worker plan in order to enable users to use IPFS in the browser like if they were using the gateway, but through js-ipfs.

**Comment by diasdavid** [comment]
Got it! Once this https://github.com/ipfs/js-ipfs/pull/968 is done and merged, port the gateway feature to a service worker! (I'm doing this anyway for Brave integration)

**Comment by lidel** [comment]
Hello from 2018 :wave: 

Service Worker Gateway is now a separate project: 
https://github.com/ipfs-shipyard/service-worker-gateway
